services:
  - type: web
    name: github-workflows-ref
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/ctunon-attom/github-workflows-ref
    branch: master
    autoDeploy: false
    healthCheckPath: /health/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://github-workflows-ref.onrender.com"
      - key: DEBUG
        value: "False"
